#!/bin/sh

# start hotkeys
sxhkd &

# look & feel
bspc config border_width         2
bspc config window_gap           8
bspc config focused_border_color "#ebbcba"
bspc config normal_border_color  "#31748f"
bspc config active_border_color  "#9ccfd8"

# layout tweaks
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# autostart
~/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/wallpapers/rosepine-moon.png &
dunst &
